name: 'Setup StackQL'

on:
  push:
    branches:
    - main
  pull_request:
jobs:
  stackql-exec-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    name: 'StackQL exec'

    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prep Google Creds (Windows)
        if: ${{ matrix.os == 'windows-latest'}}
        run: | ## use the secret to create json file
          $GoogleCreds = [System.Environment]::GetEnvironmentVariable("GOOGLE_CREDS_ENV")
          $GoogleCredsDecoded = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($GoogleCreds))
          Write-Output $GoogleCredsDecoded | Set-Content sa-key.json
        shell: pwsh
        env:
          GOOGLE_CREDS_ENV: ${{ secrets.GOOGLE_CREDS }}
    
      - name: Prep Google Creds (bash)
        if: ${{ matrix.os != 'windows-latest' }}
        shell: bash
        run: | ## use the secret to create json file
          sudo echo "${{ secrets.GOOGLE_CREDS }}" | base64 -d > sa-key.json

      - name: exec google example
        uses: ./
        with:
          auth_obj_path: './stackql_scripts/auth.json'
          query_file_path: './stackql_scripts/google-example.iql'